<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Sasha" failures="1" tests="5" name="Personal loan" time="0.08" errors="0" timestamp="14 Jul 2018 19:06:58 GMT">
  <testcase classname="test.NG_day" name="Demo" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.NG_day.Demo(NG_day.java:20)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.Test2" name="ploan" time="0.008"/>
  <testcase classname="test.Day4" name="LoginAPIHomeLoan" time="0.008"/>
  <testcase classname="test.Day4" name="MobileLoginHomeLoan" time="0.001"/>
  <testcase classname="test.Day4" name="WebloginHomeLoan" time="0.001"/>
  <testcase classname="test.NG_day" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
